export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const DEVICE_MODEL = 'DEVICE_MODEL';
export const LOCATION_MODEL = 'LOCATION_MODEL';
export const MIGRATIONLOG_MODEL = 'MIGRATIONLOG_MODEL';
export const ORGANIZATION_MODEL = 'ORGANIZATION_MODEL';

